GET http://localhost:3000/empleados

###
POST http://localhost:3000/empleados
Content-Type: application/json

{
      "nombre": "Ramon",
      "dni": "82319814H",
      "sexo": "M",
      "fecha_nacimiento": "10/02/1970",
      "salario": 3564,
      "cargo": "marketing",
      "fk_departamento": 2,
      "jefe_id": 2
}

###
PUT http://localhost:3000/empleados/14
Content-Type: application/json

{
      "nombre": "Albertito",
      "dni": "98789671Y",
      "sexo": "F",
      "fecha_nacimiento": "20/11/1995",
      "salario": 2478,
      "cargo": "limpiadora",
      "fk_departamento": 4,
      "jefe_id": 3
}

###
DELETE http://localhost:3000/empleados/13


###
GET http://localhost:3000/departamentos

###
POST http://localhost:3000/departamentos
Content-Type: application/json

{
      "nombre": "Marketing",
      "ciudad": ""
}

###
PUT http://localhost:3000/departamentos/10
Content-Type: application/json

{
      "nombre": "Marketing",
      "ciudad": "Alicante"
}

###
DELETE http://localhost:3000/departamentos/10